spring:
  datasource:
    url: jdbc:postgresql://tak-api-dev.c5gvnnjtn249.us-east-1.rds.amazonaws.com/takapi
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase-changelog.xml

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false