spring:
  datasource:
    url: jdbc:postgresql://tak-api-dv.123456789012.us-east-1.rds.amazonaws.com:5432/takapi
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security.basic.enabled: false
management.security.enabled: false

liquibase.changeLog: classpath:/liquibase-changelog.xml