spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/takapi
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#  jpa:
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  liquibase:
#    enabled: false
#    change-log: classpath:/liquibase-changelog.xml

aws:
  dynamodb:
    endpoint: http://localhost:8010

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
security.basic.enabled: false
management.security.enabled: false